In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
import time

In [5]:
df=pd.read_csv("G:/cadd/Excel File/Salary.csv")
#("File location/file name")

In [7]:
#Print top 10 data
df.head(10)

Id        EmployeeName                                        JobTitle  \
0   1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4                 NaN            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5   6      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   
6   7           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   
7   8       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS   
8   9      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)   
9  10  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88        NaN      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0        NaN      NaN  326373.19         326373.19   
5   118602.0      8601.0  189082.74      NaN  316285.74         316285.74   
6        NaN     89062.9  134426.14      NaN  315981.05         315981.05   
7  256576.96         0.0    51322.5      NaN  307899.46         307899.46   
8  176932.64    86362.68   40132.23      NaN  303427.55         303427.55   
9   285262.0         0.0   17115.73      NaN  302377.73         302377.73   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN  
5  2011    NaN  San Francisco    NaN  
6  2011    NaN  San Francisco    NaN  
7  2011    NaN  San Francisco    NaN  
8  2011    NaN  San Francisco    NaN  
9  2011    NaN  San Francisco    NaN

# Data Management

In [8]:
#1 : How many rows are there?
#2 : Which all columns are importants for valuebale data?
#3 : Unnecessary columns need to delete

In [10]:
#1 How many null values are present in given data

In [11]:
df.isnull().sum()

Id                       0
EmployeeName             1
JobTitle                 0
BasePay                606
OvertimePay              0
OtherPay                 2
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [13]:
#2 : Print the numnber of rows and columns

In [15]:
df.shape

(148654, 13)

In [12]:
#1 : How much the data is missing by percentage

In [16]:
df.isnull().sum()/148654*100

Id                    0.000000
EmployeeName          0.000673
JobTitle              0.000000
BasePay               0.407658
OvertimePay           0.000000
OtherPay              0.001345
Benefits             24.324270
TotalPay              0.000000
TotalPayBenefits      0.000000
Year                  0.000000
Notes               100.000000
Agency                0.000000
Status               74.357232
dtype: float64

In [17]:
#Delete the columns with more than 24% missing values

In [18]:
#Drop a Cloumn or Delete a Column

In [22]:
df.drop(columns=["Notes","Benefits","Status"], inplace = True)

In [24]:
# Delete all Rows if it has null values

In [25]:
df.dropna(inplace =True)

In [26]:
# Count the column entry how many a same value presentd

In [32]:
df["EmployeeName"].value_counts()

Kevin Lee               13
Richard Lee             11
William Wong            11
Steven Lee              11
Stanley Lee              9
                        ..
ALYSSA AVILES            1
John Carajan             1
Carlo A De Luzuriaga     1
Antonio  Gonzalez Jr     1
Carl  Cranford           1
Name: EmployeeName, Length: 110310, dtype: int64

In [34]:
df.head(2)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
2   3  ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay OvertimePay   OtherPay   TotalPay  TotalPayBenefits  Year  \
0  167411.18         0.0  400184.25  567595.43         567595.43  2011   
2  212739.13   106088.18    16452.6  335279.91         335279.91  2011   

          Agency  
0  San Francisco  
2  San Francisco

In [35]:
df.drop(columns=["EmployeeName","JobTitle","TotalPayBenefits","Year","Agency"], inplace = True)

In [36]:
df.head(2)

Id    BasePay OvertimePay   OtherPay   TotalPay
0   1  167411.18         0.0  400184.25  567595.43
2   3  212739.13   106088.18    16452.6  335279.91

In [37]:
# We have to work on it

In [38]:
# Chnage in object into integer or float

In [39]:
# Print unique Values that presented in the Columns

In [40]:
df.BasePay.unique()

array([167411.18, 212739.13, 118602.0, ..., '6.04', '15.5',
       'Not Provided'], dtype=object)

In [43]:
df.BasePay.replace("Not Provided",np.nan)

0         167411.18
2         212739.13
5          118602.0
7         256576.96
8         176932.64
            ...    
148649            0
148650          NaN
148651          NaN
148652          NaN
148653            0
Name: BasePay, Length: 148045, dtype: object

In [44]:
# Convert all Object/String into numeric

In [46]:
df.BasePay=pd.to_numeric(df.BasePay,errors='coerce')

In [48]:
df.BasePay.unique()

array([1.6741118e+05, 2.1273913e+05, 1.1860200e+05, ..., 6.0400000e+00,
       1.5500000e+01,           nan])

In [49]:
#Same for other columns

In [50]:
df.OvertimePay.unique()

array([0.0, 106088.18, 8601.0, ..., '102.7', '56.77', 'Not Provided'],
      dtype=object)

In [51]:
df.BasePay.replace("OvertimePay",np.nan)

0         167411.18
2         212739.13
5         118602.00
7         256576.96
8         176932.64
            ...    
148649         0.00
148650          NaN
148651          NaN
148652          NaN
148653         0.00
Name: BasePay, Length: 148045, dtype: float64

In [52]:
df.OvertimePay=pd.to_numeric(df.OvertimePay,errors='coerce')

In [53]:
df.OvertimePay.unique()

array([0.0000000e+00, 1.0608818e+05, 8.6010000e+03, ..., 1.0270000e+02,
       5.6770000e+01,           nan])

In [54]:
df.OtherPay.unique()
df.OtherPay.replace("Not Provided",np.nan)
df.OtherPay=pd.to_numeric(df.OtherPay,errors='coerce')

In [55]:
df.OvertimePay.unique()

array([0.0000000e+00, 1.0608818e+05, 8.6010000e+03, ..., 1.0270000e+02,
       5.6770000e+01,           nan])

In [56]:
df.TotalPay.unique()

array([ 5.6759543e+05,  3.3527991e+05,  3.1628574e+05, ...,
        1.2890000e+01,  6.0000000e+00, -6.1813000e+02])

In [59]:
# Remove all rows that contains NAN

In [61]:
df.dropna(inplace = True)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148041 entries, 0 to 148653
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Id           148041 non-null  int64  
 1   BasePay      148041 non-null  float64
 2   OvertimePay  148041 non-null  float64
 3   OtherPay     148041 non-null  float64
 4   TotalPay     148041 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 6.8 MB


In [63]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148041.000000  148041.000000  148041.000000  148041.000000   
mean    74194.684560   66324.128437    5084.175932    3641.350465   
std     42947.333776   42764.147896   11453.507758    7975.308532   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37015.000000   33586.500000       0.000000       0.000000   
50%     74025.000000   65006.930000       0.000000     817.080000   
75%    111640.000000   94691.050000    4694.800000    4242.100000   
max    148654.000000  319275.010000  220909.480000  400184.250000   

            TotalPay  
count  148041.000000  
mean    75049.654834  
std     50383.463228  
min      -618.130000  
25%     36955.540000  
50%     71643.410000  
75%    106025.120000  
max    567595.430000

In [64]:
df=df[df>0]

In [65]:
df

Id    BasePay  OvertimePay   OtherPay   TotalPay
0            1  167411.18          NaN  400184.25  567595.43
2            3  212739.13    106088.18   16452.60  335279.91
5            6  118602.00      8601.00  189082.74  316285.74
7            8  256576.96          NaN   51322.50  307899.46
8            9  176932.64     86362.68   40132.23  303427.55
...        ...        ...          ...        ...        ...
148645  148646        NaN          NaN        NaN        NaN
148647  148648        NaN          NaN        NaN        NaN
148648  148649        NaN          NaN        NaN        NaN
148649  148650        NaN          NaN        NaN        NaN
148653  148654        NaN          NaN        NaN        NaN

[148041 rows x 5 columns]

In [66]:
df.dropna(inplace=True)

In [67]:
df

Id    BasePay  OvertimePay   OtherPay   TotalPay
2            3  212739.13    106088.18   16452.60  335279.91
5            6  118602.00      8601.00  189082.74  316285.74
8            9  176932.64     86362.68   40132.23  303427.55
10          11  194999.39     71344.88   33149.90  299494.17
11          12   99722.00     87082.62  110804.30  297608.92
...        ...        ...          ...        ...        ...
147467  147468    1182.12       487.38      44.03    1713.53
147535  147536    1160.08       426.15      15.15    1601.38
147658  147659    1282.97        36.66      49.85    1369.48
147659  147660     426.44       273.24     431.56    1131.24
147689  147690     365.68       705.24      12.19    1083.11

[64307 rows x 5 columns]

# NEW FILE

In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
import time

In [2]:
df1=pd.read_csv("G:/cadd/Excel File/Sort_Order.csv")

In [3]:
#Add new column to the Data Frame

In [4]:
df1["Discount"]=df1["OvertimePay"]*10/100

In [5]:
df1.head(10)

EmployeeName    BasePay  OvertimePay   OtherPay   TotalPay  \
0      NATHANIEL FORD  167411.18         0.00  400184.25  567595.43   
1        GARY JIMENEZ  155966.02    245131.88        NaN  538909.28   
2      ALBERT PARDINI  212739.13    106088.18   16452.60  335279.91   
3                 NaN   77916.00     56120.71  198306.90  332343.61   
4     PATRICK GARDNER  134401.60      9737.00        NaN  326373.19   
5      DAVID SULLIVAN  118602.00      8601.00  189082.74  316285.74   
6           ALSON LEE        NaN     89062.90  134426.14  315981.05   
7       DAVID KUSHNER  256576.96         0.00   51322.50  307899.46   
8      MICHAEL MORRIS  176932.64     86362.68   40132.23  303427.55   
9  JOANNE HAYES-WHITE  285262.00         0.00   17115.73  302377.73   

   TotalPayBenefits   Discount  
0         567595.43      0.000  
1         538909.28  24513.188  
2         335279.91  10608.818  
3         332343.61   5612.071  
4         326373.19    973.700  
5         316285.74    860.100  
6         315981.05   8906.290  
7         307899.46      0.000  
8         303427.55   8636.268  
9         302377.73      0.000

In [6]:
df1["BasePay"]=df1["BasePay"]//1

In [7]:
df1.head(10)

EmployeeName   BasePay  OvertimePay   OtherPay   TotalPay  \
0      NATHANIEL FORD  167411.0         0.00  400184.25  567595.43   
1        GARY JIMENEZ  155966.0    245131.88        NaN  538909.28   
2      ALBERT PARDINI  212739.0    106088.18   16452.60  335279.91   
3                 NaN   77916.0     56120.71  198306.90  332343.61   
4     PATRICK GARDNER  134401.0      9737.00        NaN  326373.19   
5      DAVID SULLIVAN  118602.0      8601.00  189082.74  316285.74   
6           ALSON LEE       NaN     89062.90  134426.14  315981.05   
7       DAVID KUSHNER  256576.0         0.00   51322.50  307899.46   
8      MICHAEL MORRIS  176932.0     86362.68   40132.23  303427.55   
9  JOANNE HAYES-WHITE  285262.0         0.00   17115.73  302377.73   

   TotalPayBenefits   Discount  
0         567595.43      0.000  
1         538909.28  24513.188  
2         335279.91  10608.818  
3         332343.61   5612.071  
4         326373.19    973.700  
5         316285.74    860.100  
6         315981.05   8906.290  
7         307899.46      0.000  
8         303427.55   8636.268  
9         302377.73      0.000

In [8]:
 df1.shape

(28, 7)

In [9]:
df1.fillna(value=0,inplace=True)


"""is used to fill missing or NaN (Not a Number) values in a pandas DataFrame df1 with a specified value, 
which in this case is 0. Let's break down the components of this code:"""

"is used to fill missing or NaN (Not a Number) values in a pandas DataFrame df1 with a specified value, \nwhich in this case is 0. Let's break down the components of this code:"

In [10]:
df1.head(10)

EmployeeName   BasePay  OvertimePay   OtherPay   TotalPay  \
0      NATHANIEL FORD  167411.0         0.00  400184.25  567595.43   
1        GARY JIMENEZ  155966.0    245131.88       0.00  538909.28   
2      ALBERT PARDINI  212739.0    106088.18   16452.60  335279.91   
3                   0   77916.0     56120.71  198306.90  332343.61   
4     PATRICK GARDNER  134401.0      9737.00       0.00  326373.19   
5      DAVID SULLIVAN  118602.0      8601.00  189082.74  316285.74   
6           ALSON LEE       0.0     89062.90  134426.14  315981.05   
7       DAVID KUSHNER  256576.0         0.00   51322.50  307899.46   
8      MICHAEL MORRIS  176932.0     86362.68   40132.23  303427.55   
9  JOANNE HAYES-WHITE  285262.0         0.00   17115.73  302377.73   

   TotalPayBenefits   Discount  
0         567595.43      0.000  
1         538909.28  24513.188  
2         335279.91  10608.818  
3         332343.61   5612.071  
4         326373.19    973.700  
5         316285.74    860.100  
6         315981.05   8906.290  
7         307899.46      0.000  
8         303427.55   8636.268  
9         302377.73      0.000

In [11]:
mean=np.mean(df1["BasePay"]) #To Find the average 1

In [12]:
mean

183481.5357142857

In [13]:
ave=df1["BasePay"].mean()#To Find the average 2

In [14]:
ave

183481.5357142857

In [15]:
max=np.max(df1["BasePay"])

In [16]:
max

294580.0

In [17]:
max=df1["BasePay"].max()

In [18]:
max

294580.0

In [19]:
min=np.min(df1["BasePay"])

In [20]:
min

0.0

In [21]:
min=df1["BasePay"].min()

In [22]:
min

0.0

In [23]:
#Change the column name

In [24]:
df1.rename(columns={"EmployeeName":"Employee"},inplace=True)

In [25]:
df1.head(10)

Employee   BasePay  OvertimePay   OtherPay   TotalPay  \
0      NATHANIEL FORD  167411.0         0.00  400184.25  567595.43   
1        GARY JIMENEZ  155966.0    245131.88       0.00  538909.28   
2      ALBERT PARDINI  212739.0    106088.18   16452.60  335279.91   
3                   0   77916.0     56120.71  198306.90  332343.61   
4     PATRICK GARDNER  134401.0      9737.00       0.00  326373.19   
5      DAVID SULLIVAN  118602.0      8601.00  189082.74  316285.74   
6           ALSON LEE       0.0     89062.90  134426.14  315981.05   
7       DAVID KUSHNER  256576.0         0.00   51322.50  307899.46   
8      MICHAEL MORRIS  176932.0     86362.68   40132.23  303427.55   
9  JOANNE HAYES-WHITE  285262.0         0.00   17115.73  302377.73   

   TotalPayBenefits   Discount  
0         567595.43      0.000  
1         538909.28  24513.188  
2         335279.91  10608.818  
3         332343.61   5612.071  
4         326373.19    973.700  
5         316285.74    860.100  
6         315981.05   8906.290  
7         307899.46      0.000  
8         303427.55   8636.268  
9         302377.73      0.000

In [26]:
#Remove outliers

In [27]:
#df1=df1[   (df1["BasePay"]>=lower_bound) & (df1["BasePay"]<=upper_bound)   ]

In [28]:
#Add a new column to a data frame

In [29]:
#for i in df1["OtherPay"]:

In [30]:
df1["Ship_Charge"]=[i*2/100 for i in df1["OtherPay"]]

In [31]:
df1.head(10)

Employee   BasePay  OvertimePay   OtherPay   TotalPay  \
0      NATHANIEL FORD  167411.0         0.00  400184.25  567595.43   
1        GARY JIMENEZ  155966.0    245131.88       0.00  538909.28   
2      ALBERT PARDINI  212739.0    106088.18   16452.60  335279.91   
3                   0   77916.0     56120.71  198306.90  332343.61   
4     PATRICK GARDNER  134401.0      9737.00       0.00  326373.19   
5      DAVID SULLIVAN  118602.0      8601.00  189082.74  316285.74   
6           ALSON LEE       0.0     89062.90  134426.14  315981.05   
7       DAVID KUSHNER  256576.0         0.00   51322.50  307899.46   
8      MICHAEL MORRIS  176932.0     86362.68   40132.23  303427.55   
9  JOANNE HAYES-WHITE  285262.0         0.00   17115.73  302377.73   

   TotalPayBenefits   Discount  Ship_Charge  
0         567595.43      0.000    8003.6850  
1         538909.28  24513.188       0.0000  
2         335279.91  10608.818     329.0520  
3         332343.61   5612.071    3966.1380  
4         326373.19    973.700       0.0000  
5         316285.74    860.100    3781.6548  
6         315981.05   8906.290    2688.5228  
7         307899.46      0.000    1026.4500  
8         303427.55   8636.268     802.6446  
9         302377.73      0.000     342.3146

In [32]:
#Make correction to values in a column

In [33]:
df1["Employee"].replace({"NATHANIEL FORD":"Farid","ALSON LEE":"Zishan","MICHAEL MORRIS":"Rizwan"},inplace=True)

In [34]:
df1.head(10)

Employee   BasePay  OvertimePay   OtherPay   TotalPay  \
0               Farid  167411.0         0.00  400184.25  567595.43   
1        GARY JIMENEZ  155966.0    245131.88       0.00  538909.28   
2      ALBERT PARDINI  212739.0    106088.18   16452.60  335279.91   
3                   0   77916.0     56120.71  198306.90  332343.61   
4     PATRICK GARDNER  134401.0      9737.00       0.00  326373.19   
5      DAVID SULLIVAN  118602.0      8601.00  189082.74  316285.74   
6              Zishan       0.0     89062.90  134426.14  315981.05   
7       DAVID KUSHNER  256576.0         0.00   51322.50  307899.46   
8              Rizwan  176932.0     86362.68   40132.23  303427.55   
9  JOANNE HAYES-WHITE  285262.0         0.00   17115.73  302377.73   

   TotalPayBenefits   Discount  Ship_Charge  
0         567595.43      0.000    8003.6850  
1         538909.28  24513.188       0.0000  
2         335279.91  10608.818     329.0520  
3         332343.61   5612.071    3966.1380  
4         326373.19    973.700       0.0000  
5         316285.74    860.100    3781.6548  
6         315981.05   8906.290    2688.5228  
7         307899.46      0.000    1026.4500  
8         303427.55   8636.268     802.6446  
9         302377.73      0.000     342.3146

# Aggregation function fucntions on Columns

In [35]:
#Sum of columns values

In [36]:
x=df1["BasePay"].sum()

In [37]:
x

5137483.0

In [38]:
#Average of a column

In [39]:
Ave=df1["BasePay"].mean()

In [40]:
Ave

183481.5357142857

In [41]:
#Min value of a column

In [42]:
Min=df1["BasePay"].min()

In [43]:
Min

0.0

In [44]:
#Max value of a column

In [45]:
Max=df1["BasePay"].max()

In [46]:
Max

294580.0

In [47]:
#group by  column a calculate the SUM

In [48]:
Grp=df1.groupby("Employee").sum()

In [49]:
Grp

BasePay  OvertimePay   OtherPay   TotalPay  \
Employee                                                          
0                    77916.0     56120.71  198306.90  332343.61   
ALBERT PARDINI      212739.0    106088.18   16452.60  335279.91   
AMY HART            268604.0         0.00   16115.86  284720.43   
ARTHUR KENNEY       194999.0     71344.88   33149.90  299494.17   
DAVID FRANKLIN      174872.0     74050.30   37424.11  286347.05   
DAVID KUSHNER       256576.0         0.00   51322.50  307899.46   
DAVID SULLIVAN      118602.0      8601.00  189082.74  316285.74   
EDWARD HARRINGTON   294580.0         0.00       0.00  294580.02   
ELLEN MOFFATT       257510.0       880.16   16159.50  274550.25   
Farid               167411.0         0.00  400184.25  567595.43   
GARY JIMENEZ        155966.0    245131.88       0.00  538909.28   
GEORGE GARCIA       140546.0     93200.58   39955.25  273702.71   
GREGORY SUHR        256470.0         0.00   11522.18  267992.59   
JOANNE HAYES-WHITE  285262.0         0.00   17115.73  302377.73   
JOHN HANLEY          92080.0     40008.00  133695.76  265784.56   
JOHN MARTIN         271329.0         0.00   21342.59  292671.62   
JOSEPH DRISCOLL     140546.0     97868.77   31909.28  270324.91   
JUDY MELINEK        257510.0       377.21   15883.56  273771.21   
MARTY ROSS          168692.0     69626.12   38115.47  276434.22   
PATRICIA JACKSON     99722.0     87082.62  110804.30  297608.92   
PATRICK GARDNER     134401.0      9737.00       0.00  326373.19   
RAYMOND GUZMAN      168692.0     80706.88   16063.99  265463.46   
RICHARD CORRIEA     198778.0     73478.20   13957.65  286213.86   
Rizwan              176932.0     86362.68   40132.23  303427.55   
SEBASTIAN WONG      140546.0    119397.26   18625.08  278569.21   
VENUS AZAR          257510.0         0.00   16679.79  274190.27   
VICTOR WYRSCH       168692.0     77896.14   24083.86  270672.63   
Zishan                   0.0     89062.90  134426.14  315981.05   

                    TotalPayBenefits   Discount  Ship_Charge  
Employee                                                      
0                          332343.61   5612.071    3966.1380  
ALBERT PARDINI             335279.91  10608.818     329.0520  
AMY HART                   284720.43      0.000     322.3172  
ARTHUR KENNEY              299494.17   7134.488     662.9980  
DAVID FRANKLIN             286347.05   7405.030     748.4822  
DAVID KUSHNER              307899.46      0.000    1026.4500  
DAVID SULLIVAN             316285.74    860.100    3781.6548  
EDWARD HARRINGTON          294580.02      0.000       0.0000  
ELLEN MOFFATT              274550.25     88.016     323.1900  
Farid                      567595.43      0.000    8003.6850  
GARY JIMENEZ               538909.28  24513.188       0.0000  
GEORGE GARCIA              273702.71   9320.058     799.1050  
GREGORY SUHR               267992.59      0.000     230.4436  
JOANNE HAYES-WHITE         302377.73      0.000     342.3146  
JOHN HANLEY                265784.56   4000.800    2673.9152  
JOHN MARTIN                292671.62      0.000     426.8518  
JOSEPH DRISCOLL            270324.91   9786.877     638.1856  
JUDY MELINEK               273771.21     37.721     317.6712  
MARTY ROSS                 276434.22   6962.612     762.3094  
PATRICIA JACKSON           297608.92   8708.262    2216.0860  
PATRICK GARDNER            326373.19    973.700       0.0000  
RAYMOND GUZMAN             265463.46   8070.688     321.2798  
RICHARD CORRIEA            286213.86   7347.820     279.1530  
Rizwan                     303427.55   8636.268     802.6446  
SEBASTIAN WONG             278569.21  11939.726     372.5016  
VENUS AZAR                 274190.27      0.000     333.5958  
VICTOR WYRSCH              270672.63   7789.614     481.6772  
Zishan                     315981.05   8906.290    2688.5228

# Basic operation in ROWS

In [50]:
df1.head(3)

Employee   BasePay  OvertimePay   OtherPay   TotalPay  \
0           Farid  167411.0         0.00  400184.25  567595.43   
1    GARY JIMENEZ  155966.0    245131.88       0.00  538909.28   
2  ALBERT PARDINI  212739.0    106088.18   16452.60  335279.91   

   TotalPayBenefits   Discount  Ship_Charge  
0         567595.43      0.000     8003.685  
1         538909.28  24513.188        0.000  
2         335279.91  10608.818      329.052

In [51]:
#Select a ROW by in index

In [52]:
row=df1.loc[2]

In [53]:
row

Employee            ALBERT PARDINI
BasePay                   212739.0
OvertimePay              106088.18
OtherPay                   16452.6
TotalPay                 335279.91
TotalPayBenefits         335279.91
Discount                 10608.818
Ship_Charge                329.052
Name: 2, dtype: object

In [55]:
#Filtering the rows based on Conditions

In [56]:
fl=df1[df1["OtherPay"]>=20000]

In [57]:
fl

Employee   BasePay  OvertimePay   OtherPay   TotalPay  \
0              Farid  167411.0         0.00  400184.25  567595.43   
3                  0   77916.0     56120.71  198306.90  332343.61   
5     DAVID SULLIVAN  118602.0      8601.00  189082.74  316285.74   
6             Zishan       0.0     89062.90  134426.14  315981.05   
7      DAVID KUSHNER  256576.0         0.00   51322.50  307899.46   
8             Rizwan  176932.0     86362.68   40132.23  303427.55   
10     ARTHUR KENNEY  194999.0     71344.88   33149.90  299494.17   
11  PATRICIA JACKSON   99722.0     87082.62  110804.30  297608.92   
13       JOHN MARTIN  271329.0         0.00   21342.59  292671.62   
14    DAVID FRANKLIN  174872.0     74050.30   37424.11  286347.05   
18        MARTY ROSS  168692.0     69626.12   38115.47  276434.22   
22     GEORGE GARCIA  140546.0     93200.58   39955.25  273702.71   
23     VICTOR WYRSCH  168692.0     77896.14   24083.86  270672.63   
24   JOSEPH DRISCOLL  140546.0     97868.77   31909.28  270324.91   
26       JOHN HANLEY   92080.0     40008.00  133695.76  265784.56   

    TotalPayBenefits  Discount  Ship_Charge  
0          567595.43     0.000    8003.6850  
3          332343.61  5612.071    3966.1380  
5          316285.74   860.100    3781.6548  
6          315981.05  8906.290    2688.5228  
7          307899.46     0.000    1026.4500  
8          303427.55  8636.268     802.6446  
10         299494.17  7134.488     662.9980  
11         297608.92  8708.262    2216.0860  
13         292671.62     0.000     426.8518  
14         286347.05  7405.030     748.4822  
18         276434.22  6962.612     762.3094  
22         273702.71  9320.058     799.1050  
23         270672.63  7789.614     481.6772  
24         270324.91  9786.877     638.1856  
26         265784.56  4000.800    2673.9152

In [58]:
#Adding a new ROW to the DataFrame

In [59]:
New_row={"Employee":"Ansari","BasePay":3211,"OvertimePay":3244,"OtherPay":52524,"TotalPay":5252,"TotalPayBenefits":74634,"Discount":73638,"Ship_Charge":8463}

In [61]:
df1=df1.append(New_row,ignore_index=True)

In [62]:
df1.head(2)

Employee   BasePay  OvertimePay   OtherPay   TotalPay  \
0         Farid  167411.0         0.00  400184.25  567595.43   
1  GARY JIMENEZ  155966.0    245131.88       0.00  538909.28   

   TotalPayBenefits   Discount  Ship_Charge  
0         567595.43      0.000     8003.685  
1         538909.28  24513.188        0.000

In [63]:
df1.tail(2)

Employee   BasePay  OvertimePay  OtherPay   TotalPay  \
27  RAYMOND GUZMAN  168692.0     80706.88  16063.99  265463.46   
28          Ansari    3211.0      3244.00  52524.00    5252.00   

    TotalPayBenefits   Discount  Ship_Charge  
27         265463.46   8070.688     321.2798  
28          74634.00  73638.000    8463.0000

# Aggregation function on ROWS

In [64]:
#SUM of value in a row

In [85]:
df1["SUM"]=df1.sum(axis=1)
df_sorted = df1.sort_values('SUM', ascending=True)

In [86]:
df1.head(5)

Employee   BasePay  OvertimePay   OtherPay   TotalPay  \
0            Farid  167411.0         0.00  400184.25  567595.43   
1     GARY JIMENEZ  155966.0    245131.88       0.00  538909.28   
2   ALBERT PARDINI  212739.0    106088.18   16452.60  335279.91   
3                0   77916.0     56120.71  198306.90  332343.61   
4  PATRICK GARDNER  134401.0      9737.00       0.00  326373.19   

   TotalPayBenefits   Discount  Ship_Charge        Max          SUM  
0         567595.43      0.000     8003.685  567595.43  5124365.880  
1         538909.28  24513.188        0.000  538909.28  4623587.096  
2         335279.91  10608.818      329.052  335279.91  3039394.670  
3         332343.61   5612.071     3966.138  332343.61  3010248.908  
4         326373.19    973.700        0.000  326373.19  2574835.730