In [1]:
import numpy as np

In [2]:
# creating Arrays

In [3]:
List=[1,2,3,4,5] # Creating 1-D array from a List

In [4]:
arr=np.array(List)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [8]:
# creating multi dimentions arrays from List of List

In [12]:
Li1=[1,2,3,4,5]
Li2=[1,3,5,7,9]

arr1=np.array([Li1,Li2])

In [13]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 9]])

In [14]:
# Special Case of Array

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
# Identity Array

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.empty((5,5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [29]:
# Creating the Array by Range

In [35]:
arr2=np.range(2,10,2)

AttributeError: module 'numpy' has no attribute 'range'

In [38]:
arr3=np.arange(2,10)

In [39]:
arr3

array([2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr4=np.arange(2,10,2)

In [41]:
arr4

array([2, 4, 6, 8])

In [42]:
ar5=np.arange(2,10,2.5)

In [43]:
ar5

array([2. , 4.5, 7. , 9.5])

In [44]:
# Using Array and Scalars

In [46]:
ar6=np.array([[1,2,3],[4,5,6]])

In [47]:
ar6

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
ar7=ar6+ar6 # Adding Array

In [49]:
ar7

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
ar6*ar6  # Multiplying array Elemnet to element

array([[ 1,  4,  9],
       [16, 25, 36]])

In [54]:
ar6-ar6  # Substracting Array

array([[0, 0, 0],
       [0, 0, 0]])

In [57]:
# Division Array (Floating Point)

In [58]:
ar6/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [60]:
# Indexing Array

In [73]:
arr11=np.array((1,2,3,4,5,6,7,10)) # 1-D Array

In [74]:
arr11

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [75]:
arr11[1]

2

In [76]:
arr11[4]

5

In [77]:
arr11[1:3]

array([2, 3])

In [78]:
arr11[1:7]

array([2, 3, 4, 5, 6, 7])

In [81]:
# Indexing 2-D array

In [68]:
arr=np.array([[1,2,3,4,5],[1,3,5,7,9]])

In [69]:
arr

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 9]])

In [71]:
arr[1][2]  # 1st row and 2nd Column

5

In [92]:
ar2=np.array([[1,2,3,4,5],[1,3,5,7,9],[1,4,7,11,15]])

In [93]:
ar2

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 1,  4,  7, 11, 15]])

In [94]:
# arr[row,col]  or  arr[row][col]

In [95]:
ar2[1,3]

7

In [96]:
ar2[1][3]

7

In [99]:
ar2[:2,:3]   # [select the array, select the elements]

array([[1, 2, 3],
       [1, 3, 5]])

In [100]:
# Fancy indexing

In [102]:
arr=np.array([[1,2,3,4,5,6,7],[9,8,10,11,12,13,14],[15,16,17,18,19,20,21]])

In [103]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 9,  8, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [105]:
arr[0]

array([1, 2, 3, 4, 5, 6, 7])

In [106]:
arr[1]

array([ 9,  8, 10, 11, 12, 13, 14])

In [111]:
arr[:3,:2]    # [Arryas,Elements]

array([[ 1,  2],
       [ 9,  8],
       [15, 16]])

In [112]:
arr[:3,2:4]

array([[ 3,  4],
       [10, 11],
       [17, 18]])

In [113]:
#Array Transposition

In [114]:
arr=np.arange(24).reshape((4,6))

In [115]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [116]:
arr.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [117]:
# 3-D Dimention 

In [124]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [125]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [126]:
arr.ndim

3

In [129]:
ar1=np.random.randint(1,10,(4,4))

In [130]:
ar1=np.random.randint(1,10,(4,4,2))

In [131]:
ar1

array([[[9, 3],
        [3, 6],
        [6, 7],
        [5, 1]],

       [[2, 7],
        [7, 8],
        [6, 7],
        [9, 8]],

       [[7, 2],
        [9, 9],
        [7, 4],
        [5, 7]],

       [[6, 1],
        [5, 9],
        [9, 6],
        [2, 3]]])

In [132]:
ar1.ndim

3

In [133]:
ar1[1]

array([[2, 7],
       [7, 8],
       [6, 7],
       [9, 8]])

In [134]:
ar1[2]

array([[7, 2],
       [9, 9],
       [7, 4],
       [5, 7]])

In [135]:
ar1[1,2]

array([6, 7])

In [136]:
ar1

array([[[9, 3],
        [3, 6],
        [6, 7],
        [5, 1]],

       [[2, 7],
        [7, 8],
        [6, 7],
        [9, 8]],

       [[7, 2],
        [9, 9],
        [7, 4],
        [5, 7]],

       [[6, 1],
        [5, 9],
        [9, 6],
        [2, 3]]])

In [137]:
ar1.size

32

In [138]:
ar1.shape

(4, 4, 2)